#!/bin/bash
apt-get -y update

#apt-get -y install apt-transport-https
#apt-get -y update
#wget https://packages.microsoft.com/config/debian/10/packages-microsoft-prod.deb -O packages-microsoft-prod.deb
#dpkg -i packages-microsoft-prod.deb
#apt-get -y  update

apt-get -y install -y dotnet-sdk-6.0

